services:
  vuejs:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - VITE_SPECIAL_DAY=${VITE_SPECIAL_DAY}
    image: el-player-app
    pull_policy: build
    restart: always
    labels:
      # Traefik configuration discovery
      # https://doc.traefik.io/traefik/providers/docker/#routing-configuration-with-labels
      - "traefik.enable=true"
      - "traefik.http.routers.el-player-http.rule=Host(`player.docchula.com`)"
      - "traefik.http.routers.el-player-http.entrypoints=web"
      - "traefik.http.routers.el-player-https.rule=Host(`player.docchula.com`)"
      - "traefik.http.routers.el-player-https.entrypoints=websecure"
      - "traefik.http.routers.el-player-https.tls.certresolver=leresolver"
      - "traefik.http.services.el-player.loadbalancer.server.port=80"
      - "traefik.http.middlewares.el-player.compress=true"
      - "traefik.http.middlewares.el-player.compress.includedcontenttypes=application/json,text/html,text/plain"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 300M
