name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: [ self-hosted, linux, x64 ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install JS Dependencies
        run: pnpm install
      - name: Build JS assets
        run: pnpm run build
      - name: Deploy
        run: git -C /sites/el-player pull https://keenthekeen:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git && pnpm --prefix /sites/el-player install && pnpm --prefix /sites/el-player run build
